version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: notes_scolaire
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./back
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=postgres
      - DATABASE_PORT=5432
      - USER=postgres
      - PASS=admin
    depends_on:
      - postgres

  frontend:
    build: ./ui
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api
    depends_on:
      - backend

volumes:
  pgdata:
